name: "Infra: Triage: Apply triage label for PRs"
on:
  pull_request:
    types:
      - opened
jobs:
  triage_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          add-labels: "status/triage"
          ignore-if-labeled: true
