name: "Infra: Triage: Apply triage label for issues"
on:
  issues:
    types:
      - opened
jobs:
  triage_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # 1.0.4
        with:
          add-labels: "status/triage"
          ignore-if-assigned: true
